date: last-modified
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
favicon: "favicon.svg"
site-url: "https://saforem2.github.io/ml-engineering"
google-scholar: true
citeproc: true
project:
  # render: "auto"
  type: website
  output-dir: "docs"
  preview:
    port: 4596
citation:
   author:
      - name: Stas Bekman
      - name: Sam Foreman
   type: webpage
   title: "ML Engineering"
   url: "https://saforem2.github.io/ml-engineering"
execute:
  keep-ipynb: true
  # keep-md: true
  freeze: auto

metadata-files:
  - quarto/_website.yml
  - quarto/_format.yml
